apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-wg-secret
  namespace: default
spec:
  encryptedData:
    vpnConfigfile: AgBYOt4kg9LBzyh2ZN5Yne9IBgruedV+dTk7btg/a2Ybl33Lc/UMMVynlZvhMvtTDYo/KTtq32UWlUyussk2RIVrEYWAtY99+xc241usS3ODWSEJdFpvt4hd4/LMHUijwUfmsPnh2YPd0l15ug7dbe/n8mpNCuoLHufJalz+A8lyheWMKmJli0i/rs6P05my/yMZHR+GJXvokN7pzYGPfsTNypMhI6bDbHrsAnbLVRAwenyj1EmI+QLhyN7sRgAaQcYM2aPhXCc1u0h5bZKOFpuJxwNWLlWakg1PWBLJcOIoBA4b7J0yvngzFuxqOmFqZz5taQh/SbvjsFJhHX37/+Mld4KP2irzTD+Llz4fg3CPYIcFIRJW7VX+s932PUtnAWfId4OLfxEImHgumn6+BYnu4BNnFWFvyRGbmPu/vzyFo28gC5t1WKrAUHwxRzUQ7l11ewWlKBDoJAqA30ll8cJ1J6+YBsL68MPc1wXMo8vSHZ1weoX3QaN3fPxUYkUyY703HcMudw3mjNvlRqCeVxqm+THQL24vUNmxikiX9YerBV2XSpGrC5pvvpTj8EWFDnPXvb60d2OaaYsisHbfYqaVdx/hbxbqZZHk+jZiIZhTHQn0OCBN0KevNZJdqjOJt01qVRxDWX6ED2asKwDUT/moNk19sSsdyS3OK0f4iNgAvYOIOICTFNnni7TcLoEpJV6ksn5OTuIJ4iwlrhavejXYtaSmfT8SjeHu9mubfkxTOSFyErYAa+TU2DCavIOlzVgN4RHvVdER0diDTT3BumcMhYYNNDr5GYjHQHCzR29NXUP4MUomHx+EZo5dRuo2ZtnyZIyxdgGiLfGcZbi1GulaFfkpjTS1+wElY8F+Wch1saHsAZaz7PtCGqXDIm/+5lz1B7wZ8Zzaz7ddiBOMNuVQbrD2cU3ZIrax1XHQjvnzL2+A0MASs21ZWWltEYRAPrmwakxkE7chsMuIPm3ji3BP3Shrh2EEy4UeBEnGl/V+R7t/U7BG7fY94VbmC4pwaelb/7QoggY/POWaF0ZoR5EhxkZibPH4iRQf4SesA1FY
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: home-assistant-wg-secret
      namespace: default
    type: Opaque

