---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.7.4
    env:
      TZ: "Europe/Zurich"
    hostNetwork: true
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.8.39
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: hass.astutus.org
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "hass.astutus.org"
    prometheus:
      serviceMonitor:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: true
      startup:
        enabled: true
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: "1Gi"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    # addons:
      # codeserver:
      #   enabled: true
      #   image:
      #     repository: codercom/code-server
      #     tag: 3.10.2
      #   workingDir: "/config"
      #   args:
      #     - --user-data-dir
      #     - "/config/.vscode"
      #     - --auth
      #     - "none"
      #   ingress:
      #     enabled: true
      #     annotations:
      #       kubernetes.io/ingress.class: "nginx"
      #       nginx.ingress.kubernetes.io/auth-url: "https://auth.eviljungle.com/oauth2/auth"
      #       nginx.ingress.kubernetes.io/auth-signin: https://auth.eviljungle.com/oauth2/start
      #     hosts:
      #     - host: hass-vscode.eviljungle.com
      #       paths:
      #       - path: /
      #         pathType: Prefix
      #     tls:
      #     - hosts:
      #       - hass-vscode.eviljungle.com
      #   volumeMounts:
      #   - name: config
      #     mountPath: /config
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
    resources:
      limits:
        memory: 1500Mi
      requests:
        cpu: 100m
        memory: 500Mi
    postgresql:
      enabled: true
      postgresqlUsername: home-assistant
      postgresqlDatabase: home-assistant
      persistence:
        enabled: true
        storageClass: "rook-ceph-block"
  valuesFrom:
  - kind: Secret
    name: "home-assistant-helm-values"
    optional: false