apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-wg-secret
  namespace: default
spec:
  encryptedData:
    vpnConfigfile: AgAPVw2+vFQQrQ1oSBLbBqSI+FpSp3f3ng+MQsRNSZ5yOjE8FWupfb79wqawxZegSnRUPUtSIpGabIpl2cUJYzM1pwRrUA0xzs+gidzkd0ZBDDx24XzsAzO8H4buoFBJuxJfbeyIAvcFHjVxTnPLo3Vq5DEMx324zUH0MntMTySa1lfvRnQ1JTQYIBNe8kGEivDTcNquvUhWFECCYjC7iBchttAPOW6AywP7ssmCUH27xYgokV5H0k+xgwC2f4eqXD6vvPonDQTeNriZAweC8atJ2x0kmUt6Gwqr6HR1BdVaXVj5HuCCb8UmyZ0DGUfjHtEkpFETbk6h62Ln61SQ93bnq8pYjlukNpLFUoTcYECr46s1/or6C1ip0jN0ZSGPDYpjzfztRV2adzNl0dk1ovnyxCQyUBf4nqYgcArdTbkdjFLum3GlUmezr7IQ9B1IQLKlpbe7hPJbY4KOlRHIYkFAIqZqgKR/K28doogy3e3HOjZDy5rQ/Q6UZ68uhZW8v12EMai79HTfTYU6MRsWNGJg9p0rP77SCbG9gMghETy0lKEQEq6ON41dFmK1TsoHcBuDMSz570m5yOE2IlKLykxKbAAmIsJ35+Tixqwc1wt36KC9XasULYNy7aaF0E0vgHNlidBRqtDIFQ0wDFcjWJPO21rSCMbel5QdQmNVKFK39S736LNjV3eEptJApPjt7m9Dk70Qrk/9FJ34Fzmp4W1Hucaiz998EARphwV8cSb5kDz+p4MTu8uUAnGif4o3WJikLOd475HKaMSzjBEM1rzXXncTBpLAxybZRhuJChy5LPTQbTEZmoScH9S+y5h5gR95i7oBHMFBXaEnQin1JZ+JFzv8ijAhJAy+iQ4Qkd1XF8TOfFuuEkcz8v4hdVGSr1ESGwJxzu4jDZKiXn/cEWVBSLr91WY9OUOi7RotjJqBFiDatxXcF88K9XMB9qDBQIFh6m5cyEK7k1YYqnbVOcn7cHX+I+RsCreqNeRnx6b7xNmiYO3z5KMmonW83f63
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: home-assistant-wg-secret
      namespace: default
    type: Opaque

