---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2023.3.4
    env:
      TZ: "Europe/Zurich"
    # hostNetwork: true
    service:
      main:
        type: ClusterIP
        ports:
          homekit-tcp:
            enabled: true
            port: 21063
            protocol: TCP
          # homekit-udp:
          #   enabled: true
          #   port: 5353
          #   protocol: UDP
    ingress:
      main:
        enabled: true
        annotations:
          nginx.org/websocket-services: home-assistant
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: hass.astutus.org
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "hass.astutus.org"
    prometheus:
      serviceMonitor:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: true
      startup:
        enabled: true

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config

    podAnnotations:
      backup.velero.io/backup-volumes: config

    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.11.0
        workingDir: "/config"
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.astutus.org/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: https://auth.astutus.org/oauth2/start
          hosts:
          - host: hass-vscode.astutus.org
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - hass-vscode.astutus.org
        volumeMounts:
        - name: config
          mountPath: /config


    resources:
      limits:
        memory: 1500Mi
      requests:
        cpu: 100m
        memory: 500Mi
  valuesFrom:
  - kind: Secret
    name: "home-assistant-helm-values"
    optional: false