---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nut
  namespace: kube-nut
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      nut:
        replicas: 1
        strategy: Recreate

        pod:
          nodeSelector:
            feature.node.kubernetes.io/usb-03_051d_0002.present: "true"

          securityContext:
            runAsUser: 0
            runAsGroup: 0

        containers:
          app:
            image:
              repository: instantlinux/nut-upsd
              tag: latest

            env:
              TZ: "Europe/Zurich"
              DRIVER: usbhid-ups
              NAME: ups
              DESCRIPTION: "UPS"
              PORT: auto
              SERIAL: ""
              VENDORID: "051d"
              API_USER: upsmon
              API_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: nut-secret
                    key: api-password
              MAXAGE: "15"

            securityContext:
              privileged: true

            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - upsc ups@localhost:3493 2>&1|grep -q stale && exit 1 || true
                  periodSeconds: 30

            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi

    service:
      main:
        type: LoadBalancer
        controller: nut
        annotations:
          metallb.io/loadBalancerIPs: 192.168.63.233
        ports:
          http:
            port: 3493
            protocol: TCP

    persistence:
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/bus/usb
        hostPathType: Directory
        globalMounts:
          - path: /dev/bus/usb
