---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: peanut
  namespace: kube-nut
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      peanut:
        replicas: 1

        containers:
          app:
            image:
              repository: brandawg93/peanut
              tag: latest

            env:
              TZ: "Europe/Zurich"
              WEB_PORT: "8080"
              WEB_HOST: "0.0.0.0"

            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi

    service:
      main:
        type: ClusterIP
        controller: peanut
        ports:
          http:
            port: 8080
            protocol: TCP

    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "https://auth.n8r.ch/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.n8r.ch/oauth2/start"
        hosts:
          - host: peanut.n8r.ch
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - "peanut.n8r.ch"

    persistence:
      config:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /config

      settings:
        enabled: true
        type: secret
        name: nut-secret
        globalMounts:
          - path: /config/settings.yml
            subPath: peanut-settings.yml
            readOnly: true
