apiVersion: v1
kind: Secret
metadata:
    name: claper-secret
    namespace: appl-n8r
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:LJAuQEt7Rp1GhpHjzHBqr9A8t+MQAUbCogSusO1eWBcxze1Vu55uTNb/FE4SCnXzsuw3WHd5EvvHl5Nt1mL7+Z+HqYwsK9JE+N7d0PMvHLVzSkqpIcMJNQbUMwyZGHZC,iv:9ROPOrIJC+7Liaca26qWIdTxvx3sS/uHc/ssu8PSAAk=,tag:/WVIR6BaE7gneJVcUVoChw==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:hSS+FJ101BrBk+YZONZpyuzLI+gvINC7CU9tiVQKEES4iXGvCmjvNLUnB0VzCYNXbIwvDnfWb6UmDm6vVH88Kg==,iv:/glaejrRSWSMrTpovV+sOhP52XDMUak0T98x9fM54gg=,tag:tkfrzDpBQ3JOYscb5dA9EQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:+vTCZ/CE,iv:Vv9+MU5fxGO9BHJglJwRKaAcJST0J9oUy7xv9UJ2U7I=,tag:ETQB14Pt6I8fsSKQXY6XEA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Z3o61XwAukqG+rcyFXAFCwPGnDUR8IhMuD9i9EDzz6h2F2ln85E+DTZ11JrGDu275XsvCr0j+1/AKaPy,iv:y3XjgXc1dDWAjrD7R/bAQJZPJh3XX9qwiy83SGIISQ8=,tag:cdSgXwZLin5tl7fJSAjeVw==,type:str]
sops:
    age:
        - recipient: age1wtd8nd4uwzzllyy9j6eusu4hk9cjuccrgh7e47c3t64uqxact9wqx4wg2w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dU9yakpKV2krK2Vrck1L
            S0ZwOWVKSytuOVYrUEJlVHJIMXFjN0xJYTJzCllydkVEcTc5MkRZeGd6UFJpejZI
            L3dQWU5zd2dxdTgxWDVXdTVFK29mclUKLS0tIDRLWTNPcHNUdFpxbEIvZFBoSC9W
            djVhUHJQK1pRcDlFcU5SYlorTkx0YXcKaLwU31A0u/Qd5oEdZfnLytcaDOECvZPn
            yDYaGwuGPFCieKHI1UX0pOs4HFA8fTUMQKyZl/E1lkAcXmEED7oNBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T06:21:20Z"
    mac: ENC[AES256_GCM,data:naiOgBIGX84UXHten6jUGWtpkA+s/OOgN+z3tNZjmaT4uU7EQz4BQnAFp9lUXHuWyzRynZM5UqzHORGBfpSBYcYQ024/igPkeYLb1YMSxx9aTltsUN7byhUD7UayFTHBFLyC2E/SxJpRLDc5v1VokfaXrJkLhvU7gufI/8DZUqU=,iv:4yoeIF2+QYe0bEKkO6IdUbUOni2HIwWOaLXwY0VhG7c=,tag:PfFc9EfP+F2gwD9kGRD7hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
