apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: appl-home-assistant
type: Opaque
stringData:
    MARIADB_USER: ENC[AES256_GCM,data:ZU6CC9VHtbmLCBjj4tABjvZO28T9,iv:uWE0/7mD8PwUZrdPTXLpGR4nTvvtdfbwbz/6yY1UPMI=,tag:iy7an3Zc9VL93CBorGRkEA==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:ao236xWAvTrG/WhecyZIVA==,iv:aWvdfKKo+Cpzkb8YV0/mk9N8VbbspOpohSvsOTNisvg=,tag:TMbN8SA0C/fhQJzpNH1JAw==,type:str]
    MARIADB_HOST: ENC[AES256_GCM,data:hB/fASufeiLIDL2kkdFsxGy/CCtjD2ZsFA3NVitAUGHQduyKtUhI+uPQYA==,iv:HipeYf+jU6dzQbuAg8Wi6wHGJoOMDIqBydz6lNFCGYo=,tag:qTStDf/tSEENOQ5nPnqFsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtd8nd4uwzzllyy9j6eusu4hk9cjuccrgh7e47c3t64uqxact9wqx4wg2w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRGhuOGx0eVZsWU9jWW5q
            N0tHVlVKRlo5ZDJZNVh2UnhOR3dtcFhZVVhZClRnd0t2TjdWdlZraThRVCtHSVQr
            dmJVN01OMWhVMWJ0Q2tZSWpOOE94MHcKLS0tIFowNGhqMmpVK24xWlR3UWZzU2ZL
            L0NCbHFnR2RLS1RDSWh5MU5LUGNqNVkKoVWe0fSncLiXanxRXfm9bbwQb3MZRTxZ
            81cfST5YdoSPpsXNOV6rdhKW3W8MyK8/XcqHn43ZiDtTWsW1/UmQMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-17T13:54:00Z"
    mac: ENC[AES256_GCM,data:cs/JoJZsI7/aaRELE1eqIW9R9tFQ5ioeLg/MoPIt9ozhijdjgkGJAQ72EVVNAU5XcinqN0etRxgbytNawmITaocQ6fdJcx73+k2jfIKHUiLWrHArd6eQbLUk8qppm/raTH13H3kjP+FhP1rt+O6uVJCIdID4uo250dDTeKkbvOA=,iv:9LW8q5mKJBTI9irawR21RxWdTFBpWcDq5zTJeMsxLak=,tag:A/ukBr2ZEMleRh0wRMnn/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
