---
#created with: velero schedule create daily-backup --ttl=120h --schedule="0 3 * * *" -o yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  paused: false
  schedule: 0 18 * * *
  template:
    defaultVolumesToFsBackup: false
    csiSnapshotTimeout: 1h # quite long, as with only 3 nodes and 1 upload at a time it can be a long process
    snapshotVolumes: true
    snapshotMoveData: true
    storageLocation: exoscale
    excludedNamespaces:
    - appl-grafana
    - cert-manager
    - default
    - flux-system
    - kube-node-lease
    - kube-public
    - kube-system
    - kubernetes-dashboard
    - longhorn-system
    - monitoring
    - system-upgrade
    - velero
    ttl: 120h0m0s
    excludedResources:
      - secret
      - serviceaccount
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: weekly-backup
  namespace: velero
spec:
  paused: false
  schedule: "14 03 * * 6" # on saturday, at 03:14AM UTC
  template:
    defaultVolumesToFsBackup: false
    csiSnapshotTimeout: 1h # quite long, as with only 3 nodes and 1 upload at a time it can be a long process
    snapshotVolumes: true
    snapshotMoveData: true
    storageLocation: backblaze
    excludedNamespaces:
    - appl-grafana
    - cert-manager
    - default
    - flux-system
    - kube-node-lease
    - kube-public
    - kube-system
    - kubernetes-dashboard
    - longhorn-system
    - monitoring
    - system-upgrade
    - velero
    ttl:  720h0m0s
    excludedResources:
      - secret
      - serviceaccount
