---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: appl-n8r
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 10m
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      hostNetwork: true
    controllers:
      home-assistant:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2025.6.3
            env:
              TZ: "Europe/Zurich"
              # PYTHONPATH: "/config/deps"
              # UV_SYSTEM_PYTHON: "true"
              # UV_NO_CACHE: "true"
              # VENV_FOLDER: /venv
            envFrom:
              - secretRef:
                  name: home-assistant-secret
    service:
      main:
        type: ClusterIP
        controller: home-assistant
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: hass.n8r.ch
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - "hass.n8r.ch"

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config

    podAnnotations:
      backup.velero.io/backup-volumes: config

    resources:
      limits:
        memory: 1500Mi
      requests:
        cpu: 100m
        memory: 500Mi
