---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: appl-n8r
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.3-1.1.1
  enableSuperuserAccess: true

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-secret
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
        - ALTER ROLE immich SUPERUSER;

  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      max_connections: "200"

  storage:
    storageClass: longhorn-2-replicas
    size: 5Gi

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "2000m"
