---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=3
    - hard
    - noac
  nfs:
    server: 192.168.63.10
    path: /volume1/nfs-share/immich/
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: appl-n8r
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  volumeName: immich-library-nfs
