apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-secret
    namespace: appl-n8r
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ireFVE4/,iv:7VVja02p2Cx29eHmnpgsQrAXy2Yv0YamY0Cp4LZcx34=,tag:Aklzq6FFPxpY/fRME9Kr6A==,type:str]
    password: ENC[AES256_GCM,data:4vfxxFUN25qdw6Zf5qjkaHKGrhF2itU8kEzP7GSsyA==,iv:lhVvMkMg13aqn3E/lsGuoYllNjF2hjQ6ytJfUN5aD/c=,tag:YLNWvCGGm3RHBgEcB3ZlkA==,type:str]
sops:
    age:
        - recipient: age1wtd8nd4uwzzllyy9j6eusu4hk9cjuccrgh7e47c3t64uqxact9wqx4wg2w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaitMckR6bGpCdmRwSExK
            d1pxVWtISkdoZURvd2VHVUtFMGZuUE40eGlJCmNrbTNlTFljVm9NcW9uZ3ZPKzJN
            dXR0bUtHUzg1dk9wR1RBbXkwY05XREkKLS0tIEN3SWEyTzFlZTZCaEgra09GWUZp
            dGt4SFNSMDM2eHlEYWUxRFRpTDQzL1kKxk5ZphUiHDTwh8tBoMEQiywg74wtZ7w2
            MfCbWy1WN4MKtsE3FsVgwtnlj1ux2azKIr6ygtfXXgjzUA2J8fPGuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T12:20:16Z"
    mac: ENC[AES256_GCM,data:HIcM0cZMGNQ25UQTYGvueBCrdfGyhgCOLzdduHQ/Dn8TrwDC6l1na/HN5UH3F2TXTAOSHAcb8OYEyACWyv7iqBaRw0VKXOBB5gJ/hgtcurVfbg6Du+WU6YjTNEshIFEtpY+sCRMNGpfK+vG48LmTNe9ZMKVK/gYG8OD0zEYiuMw=,iv:sJIZLyJtvnSSesFRsXK44VvPVYt0+43ZTpbPe9Q/LS8=,tag:c7zilcYAhI393KRRcYPDiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
