apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: appl-n8r
type: Opaque
stringData:
    DB_URL: ENC[AES256_GCM,data:VVEo02o8yuqrxEgCPRzrR8EPTyM5TDSDssvbmIRYD0Jf3sqrLstcShOG9k6525eFv8QO0Qq3ekPCSoC44ABTEE6wfueH1FxFlRY67TfOIj5rE/Tzl/4YBx40cZ2JQrENcuraJBipiV7YR7gH7F0=,iv:qmKBodpSqo/4PdaX1bcNf0zv92sQotndCs5V8bk1LDI=,tag:fSvoq3EAgoCa2nYroNHHCg==,type:str]
sops:
    age:
        - recipient: age1wtd8nd4uwzzllyy9j6eusu4hk9cjuccrgh7e47c3t64uqxact9wqx4wg2w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyT2dOVHEyVExrRW9velp3
            b1VNSWw2Y2lCNHpCYUFKVG5pZUZ0dzV2dmswCmZ3SmhHU0pVcW1oL29qY1FvcWNS
            eVpDZ3FKSEQybU0vZ24zOEFUbDFoSTQKLS0tIEoyRDZQWmxPbWRyU01pRkhiZmxL
            cnNoTlFxL2NUVzM4Sy9VZk1JNUJLR0EKgIr3A3ymuMmqraqwlVrSLQ3GXSCVI3T4
            FMyhf+5zX6+6yTLzvYZ+/kjqzByCUSP4YDZdg3tcA5PUm57R0fC3UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T12:20:54Z"
    mac: ENC[AES256_GCM,data:7W26uMLf9KPyZzeUI0sOHp7Bi/O4n58Bb4GhVNRe8B/fZZlofUBv7i5puV3fWx+vdL4P/cGHfgPdZN7hCz+CQu2CArNV6PI3eevdkDnfnVl6zklXUg4/qHtCeN9QLZpcxckHM0Tq/MiqiEMDONIRzvxLOUaI4plLyZWyb9Nd80g=,iv:OAQMEcRUUKAABojLbL3E+xkAd/DJIHB/dH3G5iZvHAA=,tag:w3z7GFyO8+ab+ud7A6TpnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
