apiVersion: v1
kind: Secret
metadata:
    name: immich-kopia-secret
    namespace: appl-n8r
type: Opaque
stringData:
    KOPIA_S3_BUCKET: ENC[AES256_GCM,data:UG0cp/zv7g6wWeQV0Xa54VhnnaiWdVFn/Q==,iv:mcJqvXHc4eaxjy/dapHfSXbgrPTfyMLr96KCoKZHUxs=,tag:DkN/iItXHtG4Qom08YU/rA==,type:str]
    KOPIA_S3_ENDPOINT: ENC[AES256_GCM,data:hLTLWEzv8rfugFmmTmNJdS7mOOqH6V87qwQDUubyp8QL,iv:1KNJ5IeQqb1RIFBgszsAqdevb2NwJXn1zLW50O0QaFA=,tag:K6Z+Mx4pkqFNTZCSsMjkfA==,type:str]
    KOPIA_S3_ACCESS_KEY: ENC[AES256_GCM,data:Ni+/IvBG0a2rz04seXsFlO4lOW/WZAl3EA==,iv:0LFwwt03SkhUrwlGb8VCk0kPYZvPgOUobGDSmJ6ycXY=,tag:fhlXnXQBP9YPaWURjCAzog==,type:str]
    KOPIA_S3_SECRET_KEY: ENC[AES256_GCM,data:pWwuF7x249+R6UE0JcfUbYvHpcmncIl3G3wSJoYGYg==,iv:qDXArC4Nb0udY4dQHT0wLRVRPU+OTM6fLtFk2Yva+4s=,tag:5T2hNiztl15sMXXgPErC/w==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:/NJk3JCRMEw6mFjiR2WEOF4i9/V2lN5CSNEfeXpp7XNz3JLBRK4=,iv:TxF4lmlrD2JO1XD52/McPz/wyWlqHZq5AVdcUo4vRZg=,tag:zFbgNQnWiVQcqAoGm490xw==,type:str]
sops:
    age:
        - recipient: age1wtd8nd4uwzzllyy9j6eusu4hk9cjuccrgh7e47c3t64uqxact9wqx4wg2w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeVJPZ2UwcmZHR2ZQeGRE
            VkhQRzIwQkxUMVR1bjVMUlQ3ZDAxTmo0ZWs4ClRWbE9yQ2NwdEJIYmMrY1ZFdXI5
            UEN5TmVQaHV3OWFYNWpGTERmaWlVMWcKLS0tIGY1ZE5vRmVPYzVHSDB4aXZwRHpy
            eHN1Qzc5YlhVVS81L2dqUFBWQjRicTgKX1jTnDWLKikN/tCPoQ1ed8s1/gVt/6Hm
            Ps5P++WEAGegA1gkgIuj/FOmNC8IMXUUuBwQD1M0WiFRgXF74CYiIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T17:00:10Z"
    mac: ENC[AES256_GCM,data:ILaF8GbTLNq84cXvTtQqfGk01n49u19ST+aYSmI9C//fl3p1su3+wgkkAQZ+O+eSi5/EqYfClhQ6pa3Qk+gLa4U9usIFeC9nrQqKqGyUCJnvTKyEaUt8xbphXPS564xr5ame5NRb0naqWebJ8ZkwGKKj6kSZZb6xLYBgC5JHVJ4=,iv:4pyMvt8VD1mtH2gow6gUjGg9X8LqFxa7XZP3Ff4hhKk=,tag:lnrLHrNVWcNoDS1jAfFNEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
