---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-credentials
  namespace: appl-mariadb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: mariadb-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: k8s/appl-mariadb/mariadb-credentials

