
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wireguard-astutus 
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: wireguard
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:

    persistence:
      config:
        enabled: true
        mountPath: /etc/wireguard


    service:
      main:
        enabled: true
        ports:
          http:
            enabled: false
          vpn:
            enabled: true
            port: 51820
            protocol: UDP
    