
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wireguard-astutus 
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: wireguard
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      config:
        enabled: true
        mountPath: /etc/wireguard

    service:
      main:
        enabled: true
        type: NodePort
        ports:
          http:
            enabled: false
          vpn:
            enabled: true
            port: 51820
            protocol: UDP
            nodePort: 31820

    additionalContainers: 
    - name: alpine
      args:
      - while true; do sleep 30; done;
      command:
      - /bin/sh
      - -c
      - --
      image: alpine:latest
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: /etc/wireguard
        name: config
