---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kubelet-csr-approver
      version: 1.2.11
      sourceRef:
        kind: HelmRepository
        name: kubelet-csr-approver
        namespace: flux-system
      interval: 5m
  values:
    providerRegex: '^talos-node-\d*$'
    bypassDnsResolution: true
    skipDenyStep: true
