
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vm-operator
  namespace: metrics
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-metrics-operator
      version: 0.27.3
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
      interval: 5m
  values:
    operator:
      # -- By default, operator converts prometheus-operator objects.
      disable_prometheus_converter: true
      # -- By default, operator creates psp for its objects.
      psp_auto_creation_enabled: false
      # -- Enables custom config-reloader, bundled with operator.
      # It should reduce  vmagent and vmauth config sync-time and make it predictable.
      useCustomConfigReloader: false
