---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    defaultSettings:
      defaultDataPath: /storage/longhorn

# good documentation: https://rpi4cluster.com/k3s/k3s-storage-setting/#longhorn