---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ferme-roy
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s/
  prune: true
  sourceRef:
    kind: GitRepository
    name: ferme-roy

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: private-k8s-workloads
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: private-k8s-workloads
