---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k8s-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: cluster_migration
  url: https://github.com/clementnuss/k8s-gitops.git

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ferme-roy
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: ssh://git@github.com/clementnuss/ferme-roy.git