---
# ConfigMap for Kutt configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: kutt-config
  namespace: appl-n8r
data:
  PORT: "3000"
  SITE_NAME: "Kutt"
  DEFAULT_DOMAIN: "kutt.n8r.ch"
  DB_CLIENT: "mysql2"
  DB_HOST: "mariadb-service"  # Update this to match your MariaDB service name
  DB_PORT: "3306"
  DB_NAME: "kutt"
  DB_USER: "kutt"
  DB_SSL: "false"
  DB_POOL_MIN: "0"
  DB_POOL_MAX: "10"
  LINK_LENGTH: "6"
  LINK_CUSTOM_ALPHABET: "abcdefghkmnpqrstuvwxyzABCDEFGHKLMNPQRSTUVWXYZ23456789"
  TRUST_PROXY: "true"
  REDIS_ENABLED: "false"
  DISALLOW_REGISTRATION: "true"
  DISALLOW_ANONYMOUS_LINKS: "true"
  CUSTOM_DOMAIN_USE_HTTPS: "true"
  MAIL_ENABLED: "false"
  ENABLE_RATE_LIMIT: "true"
