---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.13.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicaCount: 2
      config:
        proxy-body-size: 10m
        use-forwarded-headers: "true"
        enable-real-ip: "true"
        forwarded-for-header: Cf-Connecting-Ip
        # https://www.cloudflare.com/ips-v6/#
        proxy-real-ip-cidr: "0.0.0.0/0,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32"
      service:
        watchIngressWithoutClass: true
        ingressClassResource:
          name: nginx
          enabled: true
          default: true
          controllerValue: "k8s.io/ingress-nginx"

        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: 192.168.63.239, 2001:1620:5386:cafe::80
        ipFamilyPolicy: "RequireDualStack"
        ipFamilies:
          - IPv4
          - IPv6

      metrics:
        enabled: true
      extraArgs:
        default-ssl-certificate: "cert-manager/acme-crt-secret"

      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 600Mi
    # defaultBackend:
    #   enabled: true
    #   image:
    #     repository: billimek/custom-error-pages
    #     tag: 0.4.4
    #   resources:
    #     requests:
    #       memory: 250Mi
    #       cpu: 25m
    #     limits:
    #       memory: 350Mi
