---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: descheduler
      version: 0.32.2
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
      interval: 5m
  values:
    schedule: "*/10 * * * *"
