apiVersion: v1
kind: Secret
metadata:
    name: invoiceninja-helm-values
    namespace: appl-astutus
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:yLLzV3o0NAiv2ACV5G05Y8rCuTtd0eJarnK2MLFgri8r5GcEHmIku9OFfFZX+TIF3p+hrfJCgeEn5wqInzU1Q8RANZiCYno95wLLphHPn07ZSJoIYEsQAAcrw1gVhIXDE4jTI7STvD8uTWAgpEJ9K3UunB0N7xexxWXnco4kvv7qX2dgD8EA94AfjI/ParHvk+QeuGRjdSVc/1ja79EAP0YjWvRyY+tNa9T48U6EHlmLRSbdah8osdw1q7UMkfRpvke3hGPYVApx4gGUb3Vz829W9idZ/+JpC7SifO8Rkhem3IlCmALaqs396TAObfQOoHz+h14kI0oMYCIjgA29PV/J52632EpoFzpbxGxs5pnkV4/LdgPmuiBS4o2NiaUpydhOFVnr7cU8QdOCZ43+doGLrkzB4Vvx7hE8N2tN+DrB2fQ6CfQRHQHwfe88GEd3QlnmC4dQPMT26MMoxfLdhbuGP71DcVo5TIpLv1syigbMNiLqA2zKvPZWk7oaFpfiLR45QY3ZPsIpFwFTeUznjca5hs95lq9z7RL66WM2SfloPVJH3MCqtnavD1P/HWMpsRHQYKU=,iv:yJAEzYF6w6wN20ew75c24vosKf53HREUbJHx1nbLJpQ=,tag:1yKhjwaniavxFpMgOA7ikw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtd8nd4uwzzllyy9j6eusu4hk9cjuccrgh7e47c3t64uqxact9wqx4wg2w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUS85OXducHN2SUtyMjBT
            YWE4cEo4YmlsQXVNTzAzRHpBUlUwSVVOQ2dVCm8vZmFPdFJHNGo0RzBpTWVwZVJh
            VmswdFZQREZPZHpydVRBRnFVbUtiWTgKLS0tIDdyeTdYV0w2L29Na0YxUXJ1UWtv
            UVN1Nm1GUEdWbURGUy83NW8xZzlKUkkK5xYCP6n6/COh1mr0XgSvWbQ1sadp2wXw
            xQPLdP7zNZd5D92INTb8NblgjaQEWFPppicmipNkKvL80h1mfzuEzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-30T13:51:03Z"
    mac: ENC[AES256_GCM,data:U4AMuEi1kh+riTNvB4Zr9/vtg8SJ6ljz4HcTNQX8yqLLxfwJpEgAIHIxUuAHaq/+9Dgzr8Z+RVRxJmQOQnVkCA6X2jd44BiAyBEzsiBIPiiMu6EBeZsNxhWwIK4N45lXGyYRwwZvhdsFHUyrvBEV3gEQOWbVz7L83yP+L+PocVI=,iv:B1rkpLqGtaFFw9kLM8eGPpoYoYfiCs16fc+/pA1o0/E=,tag:20H/feUp0A0tQAXB++tDGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
