---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: listmonk
  namespace: appl-n8r
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://th0th.github.io/helm-charts
      chart: listmonk
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: th0th-github-io
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/auth-url: "https://auth.n8r.ch/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: https://auth.n8r.ch/oauth2/start
      host: listmonk.n8r.ch
      enabled: true
      className: nginx

  valuesFrom:
  - kind: Secret
    name: "listmonk-helm-values"
    optional: false
