---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: listmonk-n8r
  namespace: appl-postgres
spec:
  cluster:
    name: postgres-cnpg
  name: listmonk_n8r
  owner: listmonk_n8r
  ensure: present
