apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: metrics
spec:
  podMetadata:
    labels:
      velero.io/exclude-from-backup: "true"
  selectAllByDefault: true
  scrapeInterval: 30s
  replicaCount: 2
  inlineRelabelConfig:
    - action: labeldrop
      regex: "feature_node_kubernetes_io_.+"
  remoteWriteSettings:
    useMultiTenantMode: true
  extraArgs:
     promscrape.dropOriginalLabels: "false"
  resources:
    requests:
      cpu: 200m
    limits:
      memory: 768Mi
  remoteWrite:
    - url: http://vminsert-vmcluster-short-term.metrics.svc.cluster.local:8480/insert/multitenant/prometheus/
      inlineUrlRelabelConfig:
        - action: labeldrop
          regex: "retention_period"
        - source_labels:
            [__meta_kubernetes_service_annotation_prometheus_io_tenant]
          target_label: __tenant_id__
    - url: http://vminsert-vmcluster-long-term.metrics.svc.cluster.local:8480/insert/multitenant/prometheus
      inlineUrlRelabelConfig:
        - if:
            - '{retention_period="long-term"}'
            - '{__meta_kubernetes_service_annotation_prometheus_io_retention_period="long-term"}' # not yet 100% working
          action: keep
        - action: labeldrop
          regex: "retention_period"
        - source_labels:
            [__meta_kubernetes_service_annotation_prometheus_io_tenant]
          target_label: __tenant_id__
