apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: metrics
spec:
  podMetadata:
    labels:
      velero.io/exclude-from-backup: "true"
  selectAllByDefault: true
  scrapeInterval: 30s
  replicaCount: 2
  remoteWriteSettings:
    useMultiTenantMode: true
  resources:
    requests:
      cpu: 200m
    limits:
      memory: 768Mi
  remoteWrite:
    - url: http://vminsert-vmcluster-short-term.metrics.svc.cluster.local:8480/
      inlineUrlRelabelConfig:
        - action: labeldrop
          regex: "retention_period"
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_tenant]
          target_label: __tenant_id__
    - url: http://vminsert-vmcluster-long-term.metrics.svc.cluster.local:8480/
      inlineUrlRelabelConfig:
        - source_labels: [retention_period]
          regex: "long-term"
          action: keep
        - action: labeldrop
          regex: "retention_period"
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_tenant]
          target_label: __tenant_id__
