apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster-short-term
  namespace: metrics
spec:
  retentionPeriod: "3"
  replicationFactor: 1

  vmstorage:
    replicaCount: 2
    extraArgs:
      dedup.minScrapeInterval: 30s
    storageDataPath: "/vm-data"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "app.kubernetes.io/instance"
              operator: In
              values:
              - "vmcluster-short-term"
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - "storage"
          topologyKey: "kubernetes.io/hostname"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 22Gi
    resources:
      requests:
        cpu: 200m
        memory: 1.5Gi
      limits:
        memory: 1.5Gi

  vmselect:
    image:
      tag: v1.105.0-cluster
    replicaCount: 1
    extraArgs:
      dedup.minScrapeInterval: 30s
      clusternativeListenAddr: ":8401"
    cacheMountPath: "/select-cache"
    resources:
      requests:
        cpu: 200m
      limits:
        memory: "512Mi"


  vminsert:
    replicaCount: 2
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "app.kubernetes.io/instance"
              operator: In
              values:
              - "vmcluster-short-term"
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - "vminsert"
          topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        cpu: 200m
      limits:
        memory: "1Gi"
