apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmselect
  namespace: metrics
spec:
  retentionPeriod: 1d
  vmselect:
    replicaCount: 1
    extraArgs:
      storageNode: vmselect-vmcluster-short-term.metrics:8401,vmselect-vmcluster-long-term.metrics:8401
    podMetadata:
      labels:
        velero.io/exclude-from-backup: "true"

    cacheMountPath: "/select-cache"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: "200Mi"
      limits:
        memory: "500Mi"
