apiVersion: v1
kind: Secret
metadata:
    name: paperless-kopia-secret
    namespace: appl-n8r
type: Opaque
stringData:
    KOPIA_WEBDAV_URL: ENC[AES256_GCM,data:pzq/u5LBoezr3ByRgXQPQ9X9AbIjLKt7Effv9+5ScBaIClzTPA9GSA6Oeg==,iv:sxSVe8tWPREhHso+N3kblfLc05q+F5xUEP6loH0pkPg=,tag:L5WqjyAvx2YrXrPknYIiBQ==,type:str]
    KOPIA_WEBDAV_USER: ENC[AES256_GCM,data:on20nKlH8UtgXA==,iv:oggfl3+WTDfFHOrIqcP4/BcaGbDjxPVk6ecSOS3wcLM=,tag:VYmAAWE39NIZfr0hQq+RlQ==,type:str]
    KOPIA_WEBDAV_PASS: ENC[AES256_GCM,data:dwuBWws92ow30FgbvQM=,iv:4uG3DHcJ0y74LRqGQOp3bYcqEN3GafVt4dMmnt7xMd0=,tag:YxGJKnlSV75LmdKDKldHkA==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:tliLN+W5m6C9PUl89aXHRVzIksCKp7BqLiRaHbPIKlet/lXYEAo=,iv:OeraAtQ3Wpj8Xliu0n5hwSsIOoI7FOzCxa2aoPNKJj4=,tag:4zFgR1A1TbnrjixgSwtutQ==,type:str]
sops:
    age:
        - recipient: age1wtd8nd4uwzzllyy9j6eusu4hk9cjuccrgh7e47c3t64uqxact9wqx4wg2w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHL0ZCWXloamhTK05nT2Y1
            aFNSQzMwMFA3bWhrN1pVWlBRbHBZZjhyV21RCm5GU0VDQzVmSlQyeVhrT0FrRW5I
            azB2R0ZXM1MxejJ2cVk3V0U2V3RPeDQKLS0tIHB3ZHBKNmdvNXp1N1Y5M0dVbENi
            OVhpZlZJZkVDRXc2RlAreG12M1B2ZkEKsmpclykvMXvYh5klArOgLRy+Zeq3L0k3
            ZuZpgxpASLbzXMAgUwt5FR+vKKCF/HArv3ls1sFPCBH84lfM2VYuuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T19:38:20Z"
    mac: ENC[AES256_GCM,data:/Eh7uLp4FyUuVLDWj6vedc3+4rTMJ+jw4KV+Zqiir5YsMqESM6pQMK7QqhU7I4da0jSjHlD4Ls0Ga8uOHxbFSUk/dNLZMX/ebpS/7u380pA0+B4gkCcFr2KnESRX4XWWaSaYjEWv8kBM6i/CKrawH/x4QyHmUdiRG05OpmV1pr8=,iv:d+xA22gVSpXF2IuUTwlmLDpSFquG9fAtpGggQPs5/UE=,tag:cZbl9MSUScYd+/E2/2B67w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
