---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-secret
  namespace: appl-n8r
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: paperless-ngx-secret
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: k8s/appl-n8r/paperless-ngx-secret

