---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: appl-n8r
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 10m
  uninstall:
    keepHistory: false
  values:
    controllers:
      paperless-ngx:
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.19.6
            env:
              TZ: "Europe/Zurich"
              PAPERLESS_REDIS: "redis://localhost:6379"
              PAPERLESS_TIME_ZONE: "Europe/Zurich"
              PAPERLESS_OCR_LANGUAGE: "fra+eng"
              PAPERLESS_URL: "https://paperless.n8r.ch"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_ENABLE_COLLATE_DOUBLE_SIDED: "true"
              PAPERLESS_DBENGINE: mariadb
              PAPERLESS_DBHOST: mariadb.appl-mariadb.svc.cluster.local
            envFrom:
              - secretRef:
                  name: paperless-ngx-secret
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 2Gi

          redis:
            image:
              repository: redis
              tag: 8-alpine
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 128Mi

          ftpd:
            image:
              repository: stilliard/pure-ftpd
              tag: hardened
            env:
              PUBLICHOST: "192.168.63.234"
              FTP_USER_NAME: "paperless"
              FTP_USER_PASS: "scanner123"
              FTP_USER_HOME: "/home/paperless"
              FTP_USER_UID: "1000"
              FTP_USER_GID: "1000"
              ADDED_FLAGS: "-p 30000:30005"
            resources:
              requests:
                cpu: 50m
                memory: 32Mi
              limits:
                memory: 64Mi

    service:
      main:
        type: ClusterIP
        controller: paperless-ngx
        ports:
          http:
            port: 8000

      ftp:
        type: LoadBalancer
        controller: paperless-ngx
        annotations:
          metallb.io/loadBalancerIPs: 192.168.63.234
        ports:
          ftp:
            port: 21
            targetPort: 21
          passive-30000:
            port: 30000
            targetPort: 30000
            protocol: TCP
          passive-30001:
            port: 30001
            targetPort: 30001
            protocol: TCP
          passive-30002:
            port: 30002
            targetPort: 30002
            protocol: TCP
          passive-30003:
            port: 30003
            targetPort: 30003
            protocol: TCP
          passive-30004:
            port: 30004
            targetPort: 30004
            protocol: TCP
          passive-30005:
            port: 30005
            targetPort: 30005
            protocol: TCP

    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: paperless.n8r.ch
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - "paperless.n8r.ch"

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        size: 5Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /usr/src/paperless/data

      media:
        enabled: true
        type: persistentVolumeClaim
        size: 10Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /usr/src/paperless/media

      consume:
        enabled: true
        type: persistentVolumeClaim
        size: 2Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /usr/src/paperless/consume
          - path: /home/paperless
            subPath: ""

      export:
        enabled: true
        type: persistentVolumeClaim
        size: 2Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /usr/src/paperless/export

