apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: pods
  namespace: metrics
spec:
  jobLabel: "app.kubernetes.io/name"
  podMetricsEndpoints:
    - honorLabels: true
      relabelConfigs:
        - action: keep
          regex: "true"
          sourceLabels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scrape
        - action: replace
          regex: (https?)
          sourceLabels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scheme
          targetLabel: __scheme__
        - action: replace
          regex: (.+)
          sourceLabels:
            - __meta_kubernetes_pod_annotation_prometheus_io_path
          targetLabel: __metrics_path__
        - action: keep_if_equal
          source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_port
            - __meta_kubernetes_pod_container_port_number
        - action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          sourceLabels:
            - __address__
            - __meta_kubernetes_pod_annotation_prometheus_io_port
          targetLabel: __address__
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: kubernetes_node
  namespaceSelector:
    any: true
  selector: {}
