apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secrets
    namespace: appl-n8r
type: Opaque
stringData:
    #ENC[AES256_GCM,data:8HgE1nSgu8LoaRSgHZS8ao3j1CbOHS6OgZS4jZ4mLblcKmKHYmbBG1KAPTdqdRRAfpW95WBCjFrs5qm9QLLW7dqK7uc=,iv:VM90mAi374F/47jf8FhC5IoomRv+umTo8UhUzGmFBkI=,tag:Ev4V/FwDHTEtAQmNdMNC9Q==,type:comment]
    helm-values.yaml: ENC[AES256_GCM,data:PVG18CDYqzlBo0M1b1DCuPcfjgR3mxHmZTIQJ18eXfYIbVLCC4S1GMfCi53Ty8/r6cI+LywKd+clL0C25AU/zKuNmfsZtx9jsPuF+l7aieT6vXI8/pOK+VbDrZFqfu3du6zUMXrMZikrCGSgD9c6nBC7z4QvNdNWAT6B2soETU+mdiZ1B6pip7YSt5aov6L7whKkvRd7prT0cIsmwbqM0rwN+VUL,iv:eXbQhnIujBXLUWXhG6Nmo/xugD7pp1mrRjhHq2e2PtI=,tag:rfCh2+T7E3aiI6+nvQkyXA==,type:str]
    #ENC[AES256_GCM,data:MgEt23YcyvFIi9qdFm256wquPAoLX5SQrS5ERUw+xOiNrY1ZQzB5,iv:6AB/VTXa8Av+EA5yELK4O9wMjg38K60z1Ofo3h2R+jM=,tag:vfY9XuYgS+I3XwDrB1Jx7g==,type:comment]
    allowed-emails: ENC[AES256_GCM,data:XdrzgXwiBldnBxDGQd+B6N0s6k1WZlv0OQ4KmBQI97LdAHClofF3RzmqFsfu,iv:RFE/cp0tI8146vOoT0X8LnR0LyW8I9Lp0yd4iif73hM=,tag:t1LbQVtzbedDnsq6iN1f1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWGxXd0RpR2kzcmZFWWFM
            S3RmWUtGZDlvcjl2Q2t5Y0dyb1hrUktYR0JrCitUWlY3ZWpxa01SUElNcm5YdlY3
            NklTcEhJdnRvZUhiY1ZlZmQvSytxZTQKLS0tIE54bnBTN0g5UVBXV24waE5JbzA0
            b2kwSHVxdjc0aGttcXlldE9rbjR4Z2sKf+xOv5IA4Jqz2J/41vEbg6HcChQGAhFU
            1qkjIdcpEFkTvIaa9MKpSp2eyjhu7ier3X4o41ZZfW0/gYiEGd+v/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtd8nd4uwzzllyy9j6eusu4hk9cjuccrgh7e47c3t64uqxact9wqx4wg2w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T14:40:11Z"
    mac: ENC[AES256_GCM,data:X0G/c++3HhEPIRUoBsrAFmX96rgan7UusYM7yBP2ttv0bdUUW/YPwKFc+OFid93Uu6cAyLZzyD7zJKcmJpf6lOpz3EPg05NKZ93MiqUNrVs1firhASqtUNrmO+mMtRD5qSMsONLqE6HqcrwqDPSFPNvbw4jLfHWpdij93BGGxms=,iv:CFSyawKwE30Mzkh2OobkT6GMRTsDMlJkPCUpWs1bC9E=,tag:xEi50AzdHeJ2KpHY0B4SHg==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
