apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx
  namespace: default
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
