
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://repos.emqx.io/charts
      chart: emqx
      version: 5.0.13
      sourceRef:
        kind: HelmRepository
        name: emqx-charts
        namespace: flux-system
      interval: 5m
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - apiVersion: apps/v1
        kind: StatefulSet
        metadata:
          name: emqx
        spec:
          template:
            spec:
              containers:
              - name: emqx
                volumeMounts:
                - mountPath: /opt/emqx/etc/certs
                  name: tls-cert
              volumes:
              - name: tls-cert
                secret:
                  items:
                  - key: tls.key
                    path: key.pem
                  - key: tls.crt
                    path: cert.pem
                  secretName: emqx-crt-secret
  values:
    replicaCount: 1
    recreatePods: true
    service:
      type: NodePort
      nodePorts:
        mqttssl: 30883

    persistence:
      enabled: true
      existingClaim: "emqx"
    
    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "false"
    #   EMQX_ACL_NOMATCH: "deny"

    emqxAclConfig: >
      {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
      {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
      {allow, all, subscribe, ["$SYS/#", {eq, "#"}]}.
      {allow, all}.
    emqxLoadedPlugins: >
      {emqx_management, true}.
      {emqx_recon, true}.
      {emqx_retainer, true}.
      {emqx_dashboard, true}.
      {emqx_telemetry, false}.
      {emqx_rule_engine, true}.
      {emqx_bridge_mqtt, false}.
      {emqx_auth_mnesia, true}.
      {emqx_prometheus, true}.
    emqxLoadedModules: >
      {emqx_mod_presence, true}.
      {emqx_mod_delayed, false}.
      {emqx_mod_rewrite, false}.
      {emqx_mod_subscription, false}.
      {emqx_mod_topic_metrics, true}.
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 150Mi

    ingress:
      dashboard:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/auth-url: "https://auth.astutus.org/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.astutus.org/oauth2/start
        path: /
        hosts:
        - emqx.astutus.org
        tls:
        - hosts:
          - emqx.astutus.org
  valuesFrom:
  - kind: Secret
    name: "emqx-helm-values"
    optional: false

