---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-key
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: k8s/cert-manager/cloudflare-api-key

