---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex
  namespace: appl-n8r
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.dexidp.io
      chart: dex
      version: 0.24.0
      sourceRef:
        kind: HelmRepository
        name: dex-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1

    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: dex.n8r.ch
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - dex.n8r.ch

    config:
      issuer: https://dex.n8r.ch

      storage:
        type: kubernetes
        config:
          inCluster: true

      web:
        http: 0.0.0.0:5556

      expiry:
        idTokens: 24h
        refreshTokens:
          validIfNotUsedFor: 168h  # 7 days

      oauth2:
        skipApprovalScreen: true

      # Connectors configured via secret
      # connectors: []

      # Static clients configured via secret
      # staticClients: []

  valuesFrom:
    - kind: Secret
      name: dex-secrets
      valuesKey: helm-values.yaml
