apiVersion: v1
kind: Secret
metadata:
    name: dex-secrets
    namespace: appl-n8r
type: Opaque
stringData:
    helm-values.yaml: ENC[AES256_GCM,data:cLWS0NA5mwMTmvjpMSISGDiLyQdv24xefBA/uM73ooFcd93ZASK9b3VThzSdFFyGCqm6qF4OcZ5j68jPwEC4aou9Ik31PAcARDI1vMXMUtd1j7VcVK1W8OEmiAZn9cF/P4w7Kytwc8UcPt1pE5OosML31Erdt6nfpR0yIM9GlhPEaLLgE6GFCHvrRjfE3gLTrn9WAKBVurHVzEoe4uM76WmgWYstR4qGzWz0W2MKx3/82knl0TtVoxRlTbMnGKWXTWv84MyeyFKwwC9AeOkqe/67aTwSx3LNIr7rzljk0aIcyYCulhm8oMTDzj53Sz2rH7aGPYlI3N8rlwQw+m/nf2NFn8LXuzN1Y8rjw5KE6i7Z68LEwg9gQD8KMO3HMaoNwZzV+Y+T4mkzi4SpjFK1tRi3iyOA14tznr3Na6pzYz7YpG9cMY6RHW9bn3Qwcv0wM5W8Ixf8r+Cdh0EmOeidSo68YoRwmSYUae9yB/1szK6Ma1kxZ4tCw4FjdHHFO85XEdDv2klDQE0M1uTcebxdaMUlRd91g5ufUvb3K11h47+poHct5pXLgkFTxAQHsT5M1I4+F8Y950KAOb10TZdy08yj6UT+MjLy423zq5Knnt2XUGZj7gjGUamod3P236pGshJXG6kx4QJM6LEI1rspdgQZUyyEyF7RTuMFanG0l+FLbfxOfeWT7/WJLKFoNBaf7HeJwBdil6Y4cmfMCOVsEPKYEbrcTAXyuOv8V5pfD3yGxC52ToDBkHR5MehICceg9iezB/5YzY/jEx7JavBaH+Kbw8ZyueHic2nnU8g1Flfuw8FeGE22XpMXXwcJaMKgvMNyERe0dMYd2v4v9YcJ5lYrQ2NYonQ7rIp/uS0CQCNT1hjXZrkWr6zC7yx+eCa0PD9uBouU/neY5roVgdiDG2qT6yQ8jqWg/K5bN9N0pVb7khlo1dJNrDfjU3ff1C+aL9wxw7CsWj+L+nEk8MFOChcrawmwe38JZ4HQ/xwnlDb3hvb/kX533rjoyzMRWv51u2T5yGBeOlj5u2zOrn5y/FHOC1DUW7cdl3ros6dhb0CKoS0LqjSEsFYxiy2zes9rge7/K0HT1eH+fUNynoLK/PPwOMwIN7+AxWFA5tXYwm6A824kM5YgT3ebZx6sAJe+RXXIv2o3Co5KECtSeYIreNnJaqK/B4o8kFRz73BcilzPtlK3lcbDIcCwbIWvy/g8qBoPmjirEcQxhDGYt/smFrd1GfVgk94Z+zSpWte6NL/PgL+bA58C3virdeE7lILlGu3f8OgmfZxaNqFD2EOzH4lB4lr/ZIBLkCpkVA0oMCsyUCxfPuTstnbu+IgIEMZ7Eoz6TILFXyIFZoXgkqvK+oXwypu4MyCPpE4vxp3s6STs2Lse5wZHLkbuwW+cNXDFcPoVAJXiT9cDqKW6HbHmVTn9YG4HTw01pSP8zaCsSXivCzBPPSlvHhSRPaMCFeaJSZx3B8GBw612e03PmjnHcC4GAlpJK0q4fNRg9N7iCnZ3Wt5VUia75WMmsAjYJlZxAiszG2KHJxZ/Arcz7zNa/v/Wex6BcJiu4PXQj913cFBEmJMqlxrOL+Dl868Hs/56u+XVaqO9oZEcZPc+r0r4NR/ubiSlT0m0hqp4kPrZDWNOvPee4sc2BHWRaCDMKSfBInDZwaGthjvDXUTheWDeOe3OqaYXCAgGbRLdEykDS5NBu9THq2oZ6ZeS,iv:7NPRyEGZ9HoK3nOtaEv1iaooOEDy1vFY/yhcMmx/rnQ=,tag:troJ1rvehukfc9hTB/hFlA==,type:str]
sops:
    age:
        - recipient: age1wtd8nd4uwzzllyy9j6eusu4hk9cjuccrgh7e47c3t64uqxact9wqx4wg2w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdG15dGZKSEMrNVBHL1NO
            U1d5MkN3Nyt2dms1ckppZHZpVlpIM3RoZmlRCnV5L25mcStVQjhwTWtES2pmYU9I
            NXkzbTJtc0tvOUs4TUExT0JWeVoyUWMKLS0tIFIvWjJoWGZud3UxQVZnWDVnVFVU
            L2h5ejFIUGI4RndDam0xTkhzTEJiSTAKbqZaoy4LFJyyKPNVL37FoodxUnh9i+p3
            YXi/2Hh96H0XuS8tG1h+oEzr/7UW6njBspp7iwnI7fsRCHQFSzr5og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:50:05Z"
    mac: ENC[AES256_GCM,data:EIg0i//mskJ0JoWN5mADb0WLx+hMKad88MuQXGwjpdgJKpYa6JTsiVM3u2VXibgGNhlmJjRu+QIURy/rUJf6KFSnA87UwPjW9a5yRdzBpCzu+XIr7S2A0cze8fGq58Bdc6qaQH4XnQ/9ZJIX4xYhGQguJ9VhuWeblpF2AzwXbjc=,iv:9nF68lLOvGKRPYfrdWGJsPDysX0yZjjZg83ZR7P7oWc=,tag:lhIBMElPsuLZgN1fvG7YRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
