---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: influxdb2
      version: 2.0.4
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    adminUser:
      existingSecret: influxdb2-auth

    persistence:
      name: influxdb2
      size: 5Gi

    ingress:
      enabled: true
      ingressClassName: nginx
      tls: true
      hostname: influxdb.astutus.org
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        ingress.kubernetes.io/ssl-redirect: "true"
      path: /