---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.botkube.io
      chart: botkube
      version: v1.13.0
      sourceRef:
        kind: HelmRepository
        name: botkube-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      pullPolicy: Always
  valuesFrom:
  - kind: Secret
    name: "botkube-helm-values"
    optional: false