---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: appl-grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: k8s/appl-grafana/grafana-admin

