---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: appl-postgres
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.runix.net
      chart: pgadmin4
      version: 1.50.0
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
      interval: 5m
  values:
    env:
      email: clement@n8r.ch
    existingSecret: app-admin-secret
    secretKeys:
      pgadminPasswordKey: password
    serverDefinitions:
      enabled: true
      servers:
        postgres-n8r:
          Name: "postgres n8r cluster"
          Group: "Servers"
          Port: 5432
          Username: "app_admin"
          Host: "postgres-cnpg-rw.appl-postgres.svc.cluster.local"
          SSLMode: "prefer"
          MaintenanceDB: "postgres"
    persistentVolume:
      enabled: false
      size: 1Gi
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: pgadmin.n8r.ch
          paths:
            - path: /
              pathType: Prefix
      annotations:
        nginx.ingress.kubernetes.io/auth-url: "https://auth.n8r.ch/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: https://auth.n8r.ch/oauth2/start"
