---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kyverno
      version: 2.4.1
      sourceRef:
        kind: HelmRepository
        name: kyverno-charts
        namespace: flux-system
      interval: 5m
  values:
    namespace: kube-system

    webhooks:
      # Exclude namespaces
      - namespaceSelector:
          matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: In
            values:
              - kube-system
      # Exclude objects
      # - objectSelector:
      #     matchExpressions:
      #     - key: webhooks.kyverno.io/exclude
      #       operator: DoesNotExist