---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openstack-cinder-csi
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: openstack-cinder-csi
      version: 2.26.0
      sourceRef:
        kind: HelmRepository
        name: cloud-provider-openstack
        namespace: flux-system
      interval: 5m
  values:
    secret:
      enabled: true
      create: false
      name: cinder-csi-cloud-config
      filename: cloud.conf

    storageClass:
      enabled: false

    csi:
      provisioner:
        topology: "false"
