apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cinder-csi-cloud-config
  namespace: kube-system
spec:
  encryptedData:
    cloud-config: AgBxRXAAcOocGNZX3ZA4TubL9l5v71rljYFZBHANvAb9Qapk227GwJ9yALSYzhhc/oHL3q6UNhfAfCfDkRkzCVWEcbTNQjqWUNycTC+KhRaR+dUnPYYsU4Fusq8jtPwTc3qk25HUGo18xXBORfCIGbSeNyFVzM6CHdcUTk9UUy22NGivhb87ucn0cQ6868vUhbjTHpMHSoIjpTkO7fJDInM/ck1xFeEy5cKLyfY40cnfxjAixumcqqSjsrn6/4ZWzW6rDL4DZlgnSvYIcMV7iDlsoHNuVCQcSkOGtgkxAk0p3BGWWmYZqs9dks1IX4WN9IJXKn4LnoeWM/vsOPnrXMxfEMuU2l6xlCbfBJ+vdG2el04q51RFCP7VouFw/sOH4q+HWz2CVfr+AmETwnP6INsD/ACWqUpQt24han/nUHqPVOAb7bCM0C9AYvwDD/6tFChB7dwi2UFp9x5L8FBmEP2Is0ipaW0DUCrlm/yqJLw1X3DK1Rk341IqYHAEic95JqCmwG7iNbdJ4Xc9FrkTc+9NH3uz6VGV/Y0pyJfmPvXYeHD53BF+DwRBtt2/4G//S9sZyt5+Qzg+Cq3A3Tet+C4zki/tyyY5OKV7SQBDMPGOq8AB1PUo89aIGT42tJ/WCK/3OYHeYKwYJ+0DgYwzM1YBkdUP4bFAi+oQZpZK3Q2+rG0k0HqEYvCW2NU6zAYZ6nyijJjN1qF2im5r2lyA5n3VhouJDL9CAlEUkGfemn2Ol5f87VW/9WR6yhculLZ57mMWOKpJJ7vcUrjcVdWU6t+jMVCiQRvA/gNa0kyVG/LfgQvfq83Qqfc+DaJzULgeNbC7wQ7DYAjw/U235EpLhoFc9bchLctF+kWyLcgA2qYaA7wtFmCDd25CEhiqlVeje2WjjetlllshFr0Rj8B/irGvQrn6CQ8XOkcRDP14JS01c8mrcllMyk4DnRy0HCQa8kvig6zM60GPBj5re9nOMB232fG1+MNjInhdIo7kI4hQ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cinder-csi-cloud-config
      namespace: kube-system
    type: Opaque

