---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openstack-cinder-csi
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: openstack-cinder-csi
      version: 1.4.9
      sourceRef:
        kind: HelmRepository
        name: cloud-provider-openstack
        namespace: flux-system
      interval: 5m
  values:
    secret:
      enabled: true
      create: false
      name: cinder-csi-cloud-config

    storageClass:
      enabled: true
      delete:
        isDefault: false
        allowVolumeExpansion: true
      retain:
        isDefault: true
        allowVolumeExpansion: true