---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: invoiceninja
  namespace: flux-system
spec:
  interval: 10m
  url: https://invoiceninja.github.io/dockerfiles
  timeout: 3m
