---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubenurse
  namespace: flux-system
spec:
  interval: 10m
  url: https://postfinance.github.io/kubenurse/
  timeout: 3m