---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: appl-astutus
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 10m
  uninstall:
    keepHistory: false
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2023.5.3
    env:
      TZ: "Europe/Zurich"
    envFrom:
      - secretRef:
          name: home-assistant-secret
    # hostNetwork: true
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: hass.astutus.org
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hass.astutus.org"
    prometheus:
      serviceMonitor:
        enabled: true
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: true
      startup:
        enabled: true

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config

    podAnnotations:
      backup.velero.io/backup-volumes: config

    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.13.0
        workingDir: "/config"
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/auth-url: "https://auth.astutus.org/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: https://auth.astutus.org/oauth2/start
          hosts:
            - host: hass-vscode.astutus.org
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - hass-vscode.astutus.org
        volumeMounts:
          - name: config
            mountPath: /config

    resources:
      limits:
        memory: 1500Mi
      requests:
        cpu: 100m
        memory: 500Mi
