---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.40.5
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    grafana.ini:
      unified_alerting.screenshots:
        capture: true

    persistence:
      type: pvc
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 256Mi

    imageRenderer:
      enabled: true

    admin:
      existingSecret: grafana-admin

    envFromSecret: grafana-env

    rbac:
      pspEnabled: false
      create: false

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        ingress.kubernetes.io/ssl-redirect: "true"
      path: /
      pathType: Prefix

      hosts:
        - grafana.astutus.org

      tls:
        - hosts:
            - grafana.astutus.org
