---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: s3-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: k8s/velero/s3-credentials

