apiVersion: v1
stringData:
    cloud: ENC[AES256_GCM,data:R2AuUegWIY2J8hbHkQArTpaggg4QKQ0KYjY2g+DsoSDTj74IAwyscxuzjXz/BbyvhLMNOn0dFktlQGyOL3qlp4c/RTlUsvMlSU/Y3yzr3DF0MWVODy90MDd+LFSg+sSzylwZ0CIWuToffTRSPoxBVIsjZtQ=,iv:KSOphJy2r65SinXLesJmWaF6Xum8e3ya8ztdqyNWE5w=,tag:54lAq7kTyvkjyiXttkBxWw==,type:str]
kind: Secret
metadata:
    name: s3-infomaniak
    namespace: velero
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtd8nd4uwzzllyy9j6eusu4hk9cjuccrgh7e47c3t64uqxact9wqx4wg2w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUktKOUlURjNaTTArNjgx
            TDZaRkkrOUVMWDZESFQxZ2NLc0FsVkFUZXljCnZLYVN4NUIwWk5nVC9DR05XL1Ja
            WVNjSXd3Q09qSzVVSFk1enpYci9CZHMKLS0tICtrbXp2SGVaTEVtcE13eVJhVHN6
            SEYrNGRYS2s4RjRVdnJFeUlNQXE2NVkKDvvbphU5TNQOX4v6HDTNryiOtp8QPEtY
            0A/p3s8nikEWwj0X+e15lj2xr7NZFKi6kfPUoXJ1e4wZVFJZHULAaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-19T16:00:38Z"
    mac: ENC[AES256_GCM,data:3Gk0FLkQqp7+iDgCrnsAyZwS1ab007a1iNk615xK5pjsStOj9oVlTzR6Fy7071Z1Of9X2d88seWS3IDpPa3LR8i4gnBee56nfxtk3hI/F4a4d+TXcbxKl9SUWWCLuXcf0VDDsuQuVKOGv3lYtZ9+XAjEfbvaHRCDF+AnznGxeUg=,iv:vebOia8jugaNcxDJhl3qR8bwhzYNREeBl+D647tZnZE=,tag:QnaXt1YBGQuFseC3mp+RDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
