---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 7.2.1
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/clementnuss/velero
      tag: v1.14.1-rc
    credentials:
      existingSecret: s3-credentials
    configuration:
      features: EnableCSI
      defaultVolumesToFsBackup: false
      backupSyncPeriod: 60m
      defaultRepoMaintainFrequency: 120m
      backupStorageLocation:
        - name: backblaze
          provider: aws
          credential:
            name: s3-credentials
            key: backblaze
          bucket: velero-planchettes
          config:
            region: eu-central-003
            checksumAlgorithm: ""
            # s3ForcePathStyle: true
            s3Url: https://s3.eu-central-003.backblazeb2.com
            publicUrl: https://s3.eu-central-003.backblazeb2.com
        - name: exoscale
          provider: aws
          credential:
            name: s3-credentials
            key: exoscale
          bucket: velero-planchettes
          config:
            region: ch-dk-2
            s3Url: https://sos-ch-dk-2.exo.io
            publicUrl: https://sos-ch-dk-2.exo.io

    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.11.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 500Mi
    metrics:
      enabled: true
    snapshotsEnabled: false
    deployNodeAgent: true
    installCRDs: true
    nodeAgent:
      podVolumePath: /var/lib/kubelet/pods
      privileged: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 1000Mi
