---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 5.1.3
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    credentials:
      existingSecret: s3-infomaniak
    configuration:
      defaultVolumesToFsBackup: true
      backupStorageLocation:
        - name: default
          provider: aws
          bucket: k8s-planchettes-backup
          config:
            region: us-east-1
            s3ForcePathStyle: true
            s3Url: https://fb6a4cc65b21852cc00f4c6e2e4be124.r2.cloudflarestorage.com
            publicUrl: https://fb6a4cc65b21852cc00f4c6e2e4be124.r2.cloudflarestorage.com

      # volumeSnapshotLocation:
      #   - name: aws
      #     config:
      #       region: us-east-1

    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.8.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 500Mi
    metrics:
      enabled: true
    snapshotsEnabled: false
    deployNodeAgent: true
    installCRDs: true
    nodeAgent:
      podVolumePath: /var/lib/kubelet/pods
      privileged: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 1000Mi
