---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 5m
  values:
    k8sServiceHost: 192.168.250.80
    k8sServicePort: 6443

    kubeProxyReplacement: "strict"

    prometheus:
      enabled: true

    hubble:
      enabled: true
      relay:
        enabled: true

    proxy:
      prometheus:
        enabled: false

    ipam:
      # -- Configure IP Address Management mode.
      # ref: https://docs.cilium.io/en/stable/concepts/networking/ipam/
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDRList:
          - 172.16.0.0/16
        clusterPoolIPv4MaskSize: 24
        # clusterPoolIPv6PodCIDRList:
        # - "fd00::/104"
        # -- IPv6 CIDR mask size to delegate to individual nodes for IPAM.
        # clusterPoolIPv6MaskSize: 120
        prometheus:
          enabled: true
