---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 5m
  values:
    k8sServiceHost: 10.0.0.80
    k8sServicePort: 6443

    kubeProxyReplacement: "strict"

    bpf:
      masquerade: true
    enableIPv6Masquerade: false

    ipv6:
      enabled: true

    # ipv6NativeRoutingCIDR: "2001:1600:11:4::/64"

    # extraConfig:
    #   enable-ipv6-ndp: "true"
    #   ipv6-mcast-device: "ens3"

    prometheus:
      enabled: true

    hubble:
      enabled: true
      relay:
        enabled: true

    proxy:
      prometheus:
        enabled: false

    tolerations:
      - operator: Exists

    ipam:
      # -- Configure IP Address Management mode.
      # ref: https://docs.cilium.io/en/stable/concepts/networking/ipam/
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDRList:
          - 172.16.0.0/16
        clusterPoolIPv4MaskSize: 24
        clusterPoolIPv6PodCIDRList:
          - fc00:cafe:beef:0::/104
        clusterPoolIPv6MaskSize: 120
        prometheus:
          enabled: true
