apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-lg-frontend
  namespace: appl-astutus
spec:
  selector:
    matchLabels:
      app: bird-lg-frontend
  template:
    metadata:
      labels:
        app: bird-lg-frontend
    spec:
      hostNetwork: true
      volumes:
        - name: dn42-config
          configMap:
            name: bird-lg-frontend-config
            # items:
            #   - key: bird-lg.yaml
            #     path: bird-lg.yaml

      containers:
      - name: bird-lg-frontend
        image: registry.ipv6.docker.com/xddxdd/bird-lg-go
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /etc/bird-lg
            name: dn42-config

---
apiVersion: v1
kind: Service
metadata:
  name: bird-lg-frontend
  namespace: appl-astutus
spec:
  selector:
    app: bird-lg-frontend
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bird-lg-frontend
  namespace: appl-astutus
  labels:
    name: bird-lg-frontend
spec:
  ingressClassName: nginx
  rules:
  - host: dn42.astutus.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: bird-lg-frontend
            port:
              number: 5000


