---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: goatcounter-db-secret
  namespace: appl-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: goatcounter-db-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: k8s/appl-goat-counter/goatcounter-db-secret