apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: botkube-helm-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgBVAkLNySvu1XwW9DbvPt7iP5tiXhFbYKiVFhldjzDdUuyvvaXKkqkyCzQy0+Ow+Ks168icZkeQLdeD8mpGS1+hXg5Siki5yJx6V6b3EboThEd+X2qDc48WdcTVkDV/PsnFTlD6CTu98c9f5IyXYNX/jtLeaAyEz5GyTlq9rkYAQa2PBDak355RIjr0WIKlGQdWnTdWHwZ7TWDzB3OC0bKRP2hU+/RVuzxQo1B9XNE46T9pLgxJF1QTWugT7R3uYoSMFF1rUQi//IOi6TFck54vH4GFlfWrcsyZYxthqE2SDTd5qOWtFfDyXkCtxPGPGM8dS8Hgu6qoIi2Me8+lm7ckbX1RL+gwF4ZJPEivXGNNiJe/1r5LTNhQZkTeFMsc+D71GmUvPQPoTw+9vckEG2EteiZib8XLvFNn+KnRaTfHEwUgAZkzMaKn+b1a4m2mijIiJD64lE+y/w35P3Naazypfn5aktB1e4vS5Dfqu0thp6ZtNF4/3JA9l58pwCm3aqH1QOQzDoQVXv7jxkVHbeSJTS8CBER3bEMIeyzo40CRs+tWZAhQcOOpPGMNlINtGYh96netccXhuppmhOU9DRGlEUc0wpeNoWcCfHnyYDw64yYCYoe2OU/rpz4G9h2XZg6C6twwMZ9tK8WCuhfXOb3BtjJOe4mX32rWX9rNC0ob1D7TG9glmOtN06aYOFvBq3YIHNDZPGYbcei2xbK15jCcgUw/4jSOmmUhmnNXgbqBdtAc7+6IhbdlSh8CVUetw6vTMtSIPzTypklR6h8c3/MuHk+NfAHDb6czkRGsqaoCMeiw/AG2B55usCKn8+IpPTXJKutHC6J34yqSlba1tWIo2DlDDHc19nMNJFrcWiCw89Wldb0tRLSk2kDmYR85HdVKhuERy3mYd6MK+9DEqgbba5itlgHcCxtuAs4fb9TQxeO5RnjDSwNwPSAkvNBYHahb78Qt7hCb3JFsEGEgaWl3PMnAJOi/kHfxotVaQCWx94OCXGtZjGBZyjvZypjUXE6tTMQ/J9SO6HEkbplwR1ofGl2tvo91Mh9YCSMrw+KfBi2mPjmqHB103ww7kKqTJOl+zo1nhbPHpuNoJin579rukBT9Mr0Gu9MfR/c9klHQBGWAerIeQVVeNUuoE/l73GPuMXKHzOwow9RktNDoiK3tEgTo6Zmdk/IlLK7V5gyIhHeNulENlD3cRlWX5Q7LzCpCy+0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: botkube-helm-values
      namespace: monitoring
    type: Opaque

