---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.botkube.io
      chart: botkube
      version: v0.18.0
      sourceRef:
        kind: HelmRepository
        name: infracloudio-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: infracloudio/botkube
      tag: v0.12.1
      pullPolicy: Always
    config:
      settings:
        clustername: k8s
      resources:
        - name: velero.io/v1/backups
          namespaces:
            include:
              - ".*"
          events:
            - error
          updateSetting:
            includeDiff: true
            fields:
              - status.phase
        - name: velero.io/v1/restores
          namespaces:
            include:
              - ".*"
          events:
            types:
            - error
          updateSetting:
            includeDiff: true
            fields:
              - status.phase
  valuesFrom:
  - kind: Secret
    name: "botkube-helm-values"
    optional: false