---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: appl-postgres
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 16.6.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts-oci
        namespace: flux-system
      interval: 5m
  values:
    auth:
      architecture: standalone
      existingSecret: postgres-credentials
      metrics:
        enabled: true
    primary:
      persistence:
        storageClass: longhorn-3-replicas
