apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-infomaniak
  namespace: velero
spec:
  encryptedData:
    cloud: AgAoxsd/M3DA9fS8VWms/Y1Ev2toIR+/QrqJgejoOJFvZg0sxG+s35b/5XeckbFtM+rFl0kzmqqd2a9+fBdvRDQ+P4MD64KvkGchvwBtrgu9e8NTaIdMpW2zl5/4/uLTAGYqLaNIDWh2QaBNugUtDb6QzAHICV+PN+mBx6qeokWRTTiBE53XtFNzpSK91ISkeWPZOQdgP8dhJLSXhdH9FAuBsZwLdjhf+zqQ85laWd20ccRGqH6ESaGY+zxQ2+dteNw+cxZR4JSAmQULiADLv4B0TWWOAMxDGEaxmSdEz1srdL0tSf7wOE9ZtqtCwhpTkmBgRyo2EmajPS6qHmtSIzJcRVHDdTsSkgncfK/9PBRQRclNzjGmJ89YtDAXKAfDSTAyGH/nqYxdze4PkRbJQAHUewiLv08asis4wxmMV6hVXlOfynxgrL1qXpqs4PMfUuiFJ0ifJ1CO4daaQihdqPgi1v0JxXLAtOQKG5ObRpp9h1/JXADrrDM+tRdJBIwOAcl9tGiQiIjHwKEOgT8AK8UnQ2iwKr9II3hZweULI0j4xSPfWS6pQBoQtSIiZSRycgJHtzMDuuy6lzBeEF629fVxOom7L7oCJniPJAruh2k3sH9kGmrnyvVCLygWWDWzB3MqyE3diFYYh850JjckthepHXkPtpwYUYTR/7817WzEptOHhoYRmlp6C7WLnTIY88esMMdXqjgVWNi3muBQbAdshqwgNfjartsnA8m7ov+ge5js/UDb8a2NOcrcg0tbwHauj/eCyO327hC7yhCfmTxlsIoQ6j5pFSyu4GKsn8+qhLBf/o9S8C0cz3uCusXLs/k7LzBcSmTyX/rLnfRT/C1WgcPK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: s3-infomaniak
      namespace: velero
    type: Opaque

