---
#created with: velero schedule create daily-backup --ttl=120h --schedule="0 3 * * *" -o yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  schedule: 30 12 * * *
  template:
    excludedNamespaces:
    - kube-system
    - flux-system
    ttl: 120h0m0s
  excludedResources:
    - secret
  defaultVolumesToFsBackup: true
  snapshotVolumes: false
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: weekly-backup
  namespace: velero
spec:
  schedule: "14 03 * * 1" # on monday, at 03:14AM
  template:
    excludedNamespaces:
    - kube-system
    - flux-system
    ttl:  2160h0m0s
  excludedResources:
    - secret
  defaultVolumesToFsBackup: true
  snapshotVolumes: false
