---
#created with: velero schedule create daily-backup --ttl=120h --schedule="0 3 * * *" -o yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  schedule: 0 18 * * *
  template:
    defaultVolumesToFsBackup: true
    excludedNamespaces:
    - kube-system
    - flux-system
    - system-upgrade
    ttl: 120h0m0s
    excludedResources:
      - secret
    snapshotVolumes: false
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: weekly-backup
  namespace: velero
spec:
  schedule: "14 03 * * 1" # on monday, at 03:14AM
  template:
    defaultVolumesToFsBackup: true
    excludedNamespaces:
    - kube-system
    - flux-system
    - system-upgrade
    ttl:  2160h0m0s
    excludedResources:
      - secret
    snapshotVolumes: false
