---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 5.0.2
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    credentials:
      existingSecret: s3-infomaniak
    configuration:
      provider: aws
      defaultVolumesToRestic: true
      backupStorageLocation:
        name: default
        bucket: velero
        config:
          region: us-east-1
          s3ForcePathStyle: true
          s3Url: https://s3.swiss-backup02.infomaniak.com
          publicUrl: https://s3.swiss-backup02.infomaniak.com
      volumeSnapshotLocation:
        name: aws
        config:
          region: us-east-1
      resticTimeout: 6h

    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.8.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 500Mi
    metrics:
      enabled: true
    snapshotsEnabled: false
    deployNodeAgent: true
    installCRDs: true
    nodeAgent:
      podVolumePath: /var/lib/kubelet/pods
      privileged: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 1000Mi
