apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-restic-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgB02S5dJtn/9rllbt6K+16cq1wjf8Ji45MHxGm5SUHi13oxvfDbpTUaklH0Bp6Qh0qvGa/ahBY6cYMVDox4V3hDeYqzkwqCZAJQ4cOFLZRSdaMICfQwvS/Og8u+Eui3JjVsk6mwfQ+qOmzzg7WbkaiAnBJ14rZCzDbB05THAbprQlP4dyQsqYi4juGBWhLQerRQLXNuM3jg1zJFBORsfiEai+QHWOrqmUtB+CQutK14djAzXsybhHSYyOIwqRkFgWwrKGQk4N+H8XnbhSFb01c1YRc3D8wjeQhnqjv1m7T021OeRMbQadjuwk62w96b5EFDT+upimMFiZGSKIahqjp5uIl1DlFGR5cvLSLBnkIvF50lxaJirz8gOjNp3DwQ8rkqZZNb01ril4qd5Id+m6O9DcGQlMoibEs8rjj/olmEwyJoQLDm4q1fQksS0nSmbLQsNc2PqPYYx3s1lMzE86iHb7s/XARv82jKcx/XML11X0vc167SrIrb4VeeZq18Uh77+GU/5VOpypyb31w9csBJp2exOJOcf/5kRVC7iUD4kJ5D4Owzq2ibklJzeWmFVXL1hB86ldcVPuzpui2twNf7GYR1lSn9Yef2KrSvC1PAw8xps8FSL4T10r0BQIomT/7qjml4kk5u9E+k5UJJULW91cv1OZEgBtUdERqeDvGTcPC9G22f4dsuOe18Qz8sIBeLcV1gcmzwQKw414cv4vtax4bDdeouSIhJn48O
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: velero-restic-credentials
      namespace: velero
    type: Opaque

