---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 2.24.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    credentials:
      useSecret: true
      existingSecret: s3-infomaniak
    # disabling the job, as docker image not ARM64 compatible.
    # we manually have to upgrade CRDs with the following command
    # velero install --crds-only
    upgradeCRDs: false
    configuration:
      extraSecretRef: swift-infomaniak
      provider: community.openstack.org/openstack
      defaultVolumesToRestic: true
      backupStorageLocation:
        bucket: k8s-backups
      resticTimeout: 6h

    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
    initContainers:
    - name: velero-plugin-for-openstack
      image: lirt/velero-plugin-for-openstack:v0.3.0-arm64
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 500Mi
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
    # enableHelmHooks: false
    metrics:
      enabled: true
      # serviceMonitor:
      #   enabled: true
    snapshotsEnabled: true
    deployRestic: true
    installCRDs: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      tolerations:
      # - key: "arm"
      #   operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 1000Mi
      