---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 2.26.2
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    credentials:
      existingSecret: s3-infomaniak
    # disabling the job, as docker image not ARM64 compatible.
    # we manually have to upgrade CRDs with the following command
    # velero install --crds-only
    upgradeCRDs: false
    configuration:
      provider: aws
      defaultVolumesToRestic: true
      backupStorageLocation:
        name: default
        bucket: default
        config:
          region: us-east-1
          s3ForcePathStyle: true
          s3Url: https://s3.swiss-backup02.infomaniak.com
          publicUrl: https://s3.swiss-backup02.infomaniak.com
      volumeSnapshotLocation:
        name: aws
        config:
          region: us-east-1
      resticTimeout: 6h

    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.3.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 500Mi
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
    # enableHelmHooks: false
    metrics:
      enabled: true
      # serviceMonitor:
      #   enabled: true
    snapshotsEnabled: false
    deployRestic: true
    installCRDs: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      tolerations:
      # - key: "arm"
      #   operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 1000Mi
      