---
apiVersion: v1
kind: Service
metadata:
  name: seasearch
  namespace: appl-seafile
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: seasearch
  ports:
    - name: http
      port: 4080
      targetPort: 4080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seasearch
  namespace: appl-seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: seasearch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seasearch
    spec:
      containers:
        - name: seasearch
          image: seafileltd/seasearch:1.0-latest
          env:
            - name: SS_DATA_PATH
              value: "/data"
            - name: SS_LOG_TO_STDOUT
              value: "true"
            - name: SS_FIRST_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: SEASEARCH_ADMIN_USER
            - name: SS_FIRST_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: SEASEARCH_ADMIN_PASSWORD
          ports:
            - containerPort: 4080
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 2Gi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: seasearch-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seasearch-data
  namespace: appl-seafile
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2-replicas
  resources:
    requests:
      storage: 20Gi