---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: emqx-tls
  namespace: appl-emqx
spec:
  secretName: emqx-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - emqx.n8r.ch

