apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: minio
  name: nfs-coeuve-pvc 
spec:
  capacity:
    storage: 30Gi 
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /volume1/minio
    server: 10.0.0.10
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: minio
  name: nfs-coeuve-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 30Gi