---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./infra/
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: workloads
  namespace: flux-system
spec:
  interval: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./workloads/
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: private-k8s-workloads
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: private-k8s-workloads
