apiVersion: v1
kind: Secret
metadata:
    name: filebrowser-secret
    namespace: appl-n8r
type: Opaque
stringData:
    FILEBROWSER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:buyk239gg0qMY8gknv5SScXx1Kg2ZjtVQD4IlRLJliBQDmKDXAOBAJ0xQJheLW1OalTwPTp+v0grgHsd,iv:5wHSsm4BgbBcbrrcDw/yKz/1Y5PxNkw6tUw4+3ddQYU=,tag:DxOUgpWvREyiBuMt8StjxQ==,type:str]
    FILEBROWSER_JWT_TOKEN_SECRET: ENC[AES256_GCM,data:UY20qOZ8DmcJW5pgZDUAntkxlKK14mRV7R2ThWYwK0LApA+AVtfHHMq5EVkPj3XCVdA6El/Tk273nN3s,iv:+tbPmdlrI07YJRMCk8SRIKwDBV2TvLj3Xmb4xh0n6Yk=,tag:xRTpVEIThHWqU1ieRiOLTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIckduVjRpenp4YnRsUlZJ
            b0puYWNVT2VULzFPQjBCR2tua2QwY2NGNTNZCkNaU1VKYzBZRFZPWWtLR0MrVHVO
            dWRuR2xPR0ZxNis5d0VyWHM2L2FScFUKLS0tIFhCT21QcjFFNDgrNXk4WjdaOFlx
            OHhLa3h2UXVSTGx6VTRBbHJGOG5GQlkKWXnqe4FqFoMRMrkfBQDT9mOXhr9A63yJ
            Fh/drQCaCJiM1fjRsLTVLoD4CL/i1OoZjaUqjSDpk1e4R1725+yEfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtd8nd4uwzzllyy9j6eusu4hk9cjuccrgh7e47c3t64uqxact9wqx4wg2w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T14:40:44Z"
    mac: ENC[AES256_GCM,data:kq3b0Fb6jNkPwN+H9btmzC4nwPy5VU9AI7AjSpRrdHVOg8/AG/axymHjl3puTGwzOW8SZKsk1GZnOrOXPEv9mbi4njf9ijBpCsAitEdR6ouAy0QfPjwS+D1934r/hdpoVSrddzH2psYsL1HxmTMmdtQZKaY3rSQI9+pjjrUla1s=,iv:8SCTbky4/VEpETu1fhg0rogc2OGtYQJk0+Ndi5WUyXQ=,tag:xB6IvlXlDPab81CNSqxN+g==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
