---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victorialogs
  namespace: kube-log
spec:
  interval: 5m
  chart:
    spec:
      version: 0.9.3
      chart: victoria-logs-single
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
      interval: 5m
  values:
    server:
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "https://auth.n8r.ch/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.n8r.ch/oauth2/start
        ingressClassName: nginx
        hosts:
          - name: logs.n8r.ch
            path:
              - /
            port: http

      retentionPeriod: 10w
      persistentVolume:
        enabled: true
    vector:
      enabled: true
