---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 8.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nodered/node-red
      tag: 2.0.2-12-minimal
    env:
      TZ: "Europe/Zurich"
      FLOWS: "flows.json"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "https://auth.astutus.org/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.astutus.org/oauth2/start
        hosts:
        - host: node-red.astutus.org
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "node-red.astutus.org"
    persistence:
      data:
        enabled: true
        mountPath: /data
        existingClaim: node-red-data

    podAnnotations:
      backup.velero.io/backup-volumes: data

    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi