apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cinder-sc-retain
