---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 3.34.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicaCount: 1
      config:
        # hsts-max-age: "31449600"
      use-forwarded-headers: "true"
      service:
        loadBalancerIP: 192.168.8.40
        externalTrafficPolicy: Local
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: kube-system
        prometheusRule:
          enabled: false
      extraArgs:
        default-ssl-certificate: "cert-manager/acme-crt-secret"
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app.kubernetes.io/name
      #           operator: In
      #           values:
      #           - ingress-nginx
      #         - key: app.kubernetes.io/instance
      #           operator: In
      #           values:
      #           - ingress-nginx
      #         - key: app.kubernetes.io/component
      #           operator: In
      #           values:
      #           - controller
      #       topologyKey: "kubernetes.io/hostname"

      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 600Mi
    # defaultBackend:
    #   enabled: true
    #   image:
    #     repository: billimek/custom-error-pages
    #     tag: 0.4.4
    #   resources:
    #     requests:
    #       memory: 250Mi
    #       cpu: 25m
    #     limits:
    #       memory: 350Mi