---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://oauth2-proxy.github.io/manifests
      chart: oauth2-proxy
      version: 5.0.2
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    ingress:
      enabled: true
      className: nginx
      path: /oauth2
      hosts: [auth.astutus.org]
      tls:
      - hosts:
        - auth.astutus.org
    extraArgs:
      provider: google
      skip-provider-button:
      pass-authorization-header:
      # email-domain: "*"
      # google-group: "k8s-at-home-clementnuss"
      cookie-domain: .astutus.org
      whitelist-domain: .astutus.org
    
    config:
      configFile: |-
        email_domains = [ ]
        upstreams = [ "file:///dev/null" ]
  valuesFrom:
  - kind: Secret
    name: "oauth2-proxy-helm-values"
    optional: false