apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth2-proxy-helm-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgAjyfUnepcOWazmAzx8mzjTvomFZoV9TRWWP3ne/dS+iKcaf3X1lEhMQpbbnAje5E43uhgFejz+mkdQlvYzMrVPYBTh5lII49soSAltUPH2n8u5kIapyZVDmsx9u6814YnZrR29xW0gpIR3Am9P1jdhejGJumGO8Bkx0TQ1nT9CTOSJK+u2eNnVjsf5vxn7f4EnFkbwaTtEYUMXdTepr/toCQiYVzUSi7bWB65/eNc2iwO//tXdqd3F5Ea6IOdkN022VUnCsr6/wMEoLvCD2p/SKnnXqTv5tmFLEvCWZuQillu6iMUMrndde3VQlihRmGGzDuM5BwnpQ0zNeLjRrR6RSe2hyH7Qs3nrmdUAdwLd37LuMekqMc0nYr3brC72wgIv/73wWOxmjr/10fmc020d8UMGulzJBdvlaS1YZfw5QXipqd7I3LwOYysosm+HLcj4XXJz7zps6lXuRq8+fhVlE/TGMtcbZAE83uj8XTJPzma4d8SJ+XdeNtgRyLNYNpz4ABlYkbVKrq8pZokyPRNt0Kr5y9kwPqdGW3YG3g8Qt+xO2cQjx8Z93Uh/Aki17+r1OBtXS0mF2rQo3lBGo4aTVr+SK4yJgchVyeEn3S1IjWERgnyIW+sgd/XwQWbeKqKbIQMgbO+W1/GInmEshJo7WVWFaHPSILqZXAqPgnYrlful2JJAwB81HL7yHrpsncbtiYj8jAyOxsn767h29JECltDZPhgFGN98k3C6QzqItxx9GGTGgeUEtRW0v7P0t496COFJaPUsj2uBkyTPiBeU1PmvXuJkzyHoRS3OhNp9VG+lsVbrd914lx6IvUDyRpqDlsl+3WyuV4d11t7x4b1l9OIu1cDzyEyfsCqtwwvawnhbLvwlnYJsnaqDqqAy0DJD+STI6ikVoMe8Ok0AgD+ruOwL0OpkUAaj11TwylEzLf0nTPNW7ceaemKMx8zW7qpES9CQpTCfiNyl3dCw0KYFbAv/qRS0Nd2XZMKC5V5fjrQ5vxKJKiCc7JI+4C8lHKSf0HaKu/rFhHmhwXVu5KrK0aFQzGWKqwFAxcFnza/ls052GMbdmunuri+lf6SR2gKO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: oauth2-proxy-helm-values
      namespace: kube-system
    type: Opaque

