---
clusterName: planchettes63
talosVersion: v1.10.6
kubernetesVersion: v1.31.9
endpoint: https://192.168.63.80:6443
allowSchedulingOnControlPlanes: true
additionalApiServerCertSans:
  - "${CONTROLPLANE_ENDPOINT}"
clusterPodNets:
  - 172.16.0.0/16
  - 2001:1620:5386:beef:0::/96
clusterSvcNets:
  - 172.30.0.0/16
  - fc00:cafe:beef:ffff::/112
cniConfig:
  name: none
nodes:
  - hostname: talos-node-01
    ipAddress: 192.168.63.193
    installDisk: /dev/nvme0n1
    controlPlane: true
    networkInterfaces:
      - interface: eno1
        dhcp: true
        vip:
          ip: 192.168.63.80
  - hostname: talos-node-02
    ipAddress: 192.168.63.181
    installDisk: /dev/nvme0n1
    controlPlane: true
    networkInterfaces:
      - interface: eno1
        dhcp: true
        vip:
          ip: 192.168.63.80
  - hostname: talos-node-03
    ipAddress: 192.168.63.141
    installDisk: /dev/nvme0n1
    controlPlane: true
    networkInterfaces:
      - interface: eno1
        dhcp: true
        vip:
          ip: 192.168.63.80
  - hostname: talos-node-04
    ipAddress: 192.168.63.107
    installDisk: /dev/nvme0n1
    controlPlane: true
    networkInterfaces:
      - interface: eno1
        dhcp: true
        vip:
          ip: 192.168.63.80
  # - hostname: talos-arm64-vm
  #   ipAddress: 192.168.63.114
  #   installDisk: /dev/vda
  #   controlPlane: true
  #   nodeTaints:
  #     arm64: "NoSchedule"
patches:
  - |-
    cluster:
      controllerManager:
        extraArgs:
          allocate-node-cidrs: false
          node-cidr-mask-size-ipv6: 112
  - |-
    cluster:
      proxy:
        disabled: true
      discovery:
        enabled: true
  - |-
    machine:
      features:
        hostDNS:
          enabled: false
          forwardKubeDNSToHost: false
  - |-
    - op: add
      path: /machine/kubelet/extraConfig
      value:
        serverTLSBootstrap: true
controlPlane:
  # patches:
  #   - |-
  #     - op: add
  #       path: /machine/kubelet/extraMounts
  #       value:
  #         - destination: /var/lib/longhorn
  #           type: bind
  #           source: /var/lib/longhorn
  #           options:
  #             - bind
  #             - rshared
  #             - rw
  patches:
    - |-
      - op: remove
        path: /machine/nodeLabels/node.kubernetes.io~1exclude-from-external-load-balancers
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
          # - siderolabs/nut-client
worker:
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraMounts
        value:
          - destination: /var/lib/longhorn
            type: bind
            source: /var/lib/longhorn
            options:
              - bind
              - rshared
              - rw
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
