apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster-long-term
  namespace: metrics
spec:
  retentionPeriod: "10y"
  replicationFactor: 1

  vmstorage:
    replicaCount: 1
    extraArgs:
      dedup.minScrapeInterval: 300s
    storageDataPath: "/vm-data"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi
    resources:
      limits:
        cpu: "2"
        memory: 2048Mi

  vmselect:
    replicaCount: 1
    extraArgs:
      dedup.minScrapeInterval: 300s


  vminsert:
    replicaCount: 1
    resources:
      limits:
        cpu: "0.5"
        memory: "500Mi"
