apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster-long-term
  namespace: metrics
spec:
  retentionPeriod: "10y"
  replicationFactor: 1

  vmstorage:
    replicaCount: 1
    extraArgs:
      dedup.minScrapeInterval: 300s
    storageDataPath: "/vm-data"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi
    resources:
      requests:
        cpu: 200m
      limits:
        memory: "1Gi"

  vmselect:
    replicaCount: 1
    extraArgs:
      dedup.minScrapeInterval: 300s
      clusternativeListenAddr: ":8401"
    cacheMountPath: "/select-cache"
    resources:
      requests:
        cpu: 200m
      limits:
        memory: "0.5Gi"

  vminsert:
    replicaCount: 1
    resources:
      requests:
        cpu: 200m
      limits:
        memory: "0.5Gi"
