apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmselect
  namespace: metrics
spec:
  retentionPeriod: 1d
  vmselect:
    replicaCount: 2
    extraArgs:
      storageNode: vmselect-vmcluster-short-term.metrics:8401,vmselect-vmcluster-long-term.metrics:8401

    cacheMountPath: "/select-cache"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: "200Mi"
      limits:
        cpu: 500m
        memory: "500Mi"
