apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-external-v6
  namespace: kube-system
spec:
  ipAddressPools:
  - k8s-net

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k8s-net
  namespace: kube-system
spec:
  addresses:
  - 2001:1600:11:4:cafe:beef::/96
  - 10.0.0.224/28
